const { createAmenitiesFromSelection, createUnitStructure } = require('./factories');

const DEMO_USER_ID = 'user-aarav';
const SUPER_USER_ID = 'user-super-admin';

const amenityLibrary = [
  'Clubhouse Hall',
  'Gym',
  'Swimming Pool',
  'Tennis Court',
  'Guest Parking',
  'Party Lawn',
  'Garden',
  'Walking Track',
  'Community Hall',
];

const defaultSetupDraft = {
  societyName: '',
  country: 'India',
  state: 'Gujarat',
  city: 'Ahmedabad',
  area: '',
  address: '',
  structure: 'apartment',
  enabledStructures: ['apartment'],
  commercialSpaceType: 'shed',
  enabledCommercialSpaceTypes: ['shed'],
  apartmentUnitCount: '48',
  bungalowUnitCount: '',
  shedUnitCount: '',
  officeFloorPlan: [{ floorLabel: 'Ground Floor', officeNumbers: '' }],
  totalUnits: '48',
  maintenanceDay: '10',
  maintenanceAmount: '6500',
  selectedAmenities: ['Clubhouse Hall', 'Gym', 'Guest Parking'],
  rulesSummary:
    'Gate closure at 11:30 PM. Major amenity events require committee approval. Domestic staff must be registered with phone number and employer unit.',
};

const greenSocietyId = 'society-green-vista';
const palmSocietyId = 'society-palm-meadows';

const greenStructure = createUnitStructure(greenSocietyId, 'apartment', 24);
const palmStructure = createUnitStructure(palmSocietyId, 'bungalow', 12);

const greenAmenitySetup = createAmenitiesFromSelection(greenSocietyId, [
  'Clubhouse Hall',
  'Gym',
  'Swimming Pool',
  'Guest Parking',
  'Garden',
]);
const palmAmenitySetup = createAmenitiesFromSelection(palmSocietyId, [
  'Community Hall',
  'Party Lawn',
  'Walking Track',
  'Guest Parking',
]);

const allUnits = [...greenStructure.units, ...palmStructure.units];

function findUnitId(societyId, code) {
  return allUnits.find((unit) => unit.societyId === societyId && unit.code === code)?.id ?? '';
}

const seedData = {
  users: [
    {
      id: SUPER_USER_ID,
      name: 'Society Super User',
      phone: '+91 98980 99999',
      email: 'superuser@societyos.example',
      avatarInitials: 'SU',
    },
    {
      id: DEMO_USER_ID,
      name: 'Aarav Mehta',
      phone: '+91 98980 11111',
      email: 'aarav@resident.example',
      avatarInitials: 'AM',
    },
    {
      id: 'user-neha',
      name: 'Neha Shah',
      phone: '+91 98980 22222',
      email: 'neha@resident.example',
      avatarInitials: 'NS',
    },
    {
      id: 'user-rohan',
      name: 'Rohan Patel',
      phone: '+91 98980 33333',
      email: 'rohan@resident.example',
      avatarInitials: 'RP',
    },
    {
      id: 'user-kavya',
      name: 'Kavya Iyer',
      phone: '+91 98980 44444',
      email: 'kavya@resident.example',
      avatarInitials: 'KI',
    },
  ],
  societies: [
    {
      id: greenSocietyId,
      name: 'Green Vista Apartments',
      country: 'India',
      state: 'Gujarat',
      city: 'Ahmedabad',
      area: 'Prahladnagar',
      address: 'Prahladnagar Road, Ahmedabad',
      structure: 'apartment',
      commercialSpaceType: null,
      officeFloorPlan: [],
      timezone: 'Asia/Kolkata',
      totalUnits: 24,
      maintenanceDayOfMonth: 10,
      maintenanceAmount: 6500,
      tagline: 'High-rise community with 2 towers and shared recreation deck',
      createdAt: '2026-01-04T09:00:00.000Z',
    },
    {
      id: palmSocietyId,
      name: 'Palm Meadows Bungalows',
      country: 'India',
      state: 'Gujarat',
      city: 'Ahmedabad',
      area: 'Bopal',
      address: 'Bopal Extension, Ahmedabad',
      structure: 'bungalow',
      commercialSpaceType: null,
      officeFloorPlan: [],
      timezone: 'Asia/Kolkata',
      totalUnits: 12,
      maintenanceDayOfMonth: 8,
      maintenanceAmount: 5200,
      tagline: 'Gated villa cluster with party lawn and walking track',
      createdAt: '2026-01-14T09:00:00.000Z',
    },
  ],
  buildings: [...greenStructure.buildings, ...palmStructure.buildings],
  units: allUnits,
  memberships: [
    {
      id: 'membership-aarav-green',
      userId: DEMO_USER_ID,
      societyId: greenSocietyId,
      roles: ['owner', 'committee'],
      unitIds: [findUnitId(greenSocietyId, 'A-101')],
      isPrimary: true,
    },
    {
      id: 'membership-aarav-palm',
      userId: DEMO_USER_ID,
      societyId: palmSocietyId,
      roles: ['owner'],
      unitIds: [findUnitId(palmSocietyId, 'Plot 07')],
      isPrimary: false,
    },
    {
      id: 'membership-neha-green',
      userId: 'user-neha',
      societyId: greenSocietyId,
      roles: ['tenant'],
      unitIds: [findUnitId(greenSocietyId, 'A-202')],
      isPrimary: true,
    },
    {
      id: 'membership-rohan-green',
      userId: 'user-rohan',
      societyId: greenSocietyId,
      roles: ['owner'],
      unitIds: [findUnitId(greenSocietyId, 'B-101')],
      isPrimary: true,
    },
    {
      id: 'membership-kavya-palm',
      userId: 'user-kavya',
      societyId: palmSocietyId,
      roles: ['tenant'],
      unitIds: [findUnitId(palmSocietyId, 'Plot 11')],
      isPrimary: true,
    },
  ],
  joinRequests: [],
  residenceProfiles: [],
  occupancy: [
    {
      id: 'occupancy-aarav-green',
      societyId: greenSocietyId,
      unitId: findUnitId(greenSocietyId, 'A-101'),
      userId: DEMO_USER_ID,
      category: 'owner',
      startDate: '2025-04-01',
    },
    {
      id: 'occupancy-aarav-palm',
      societyId: palmSocietyId,
      unitId: findUnitId(palmSocietyId, 'Plot 07'),
      userId: DEMO_USER_ID,
      category: 'owner',
      startDate: '2025-10-15',
    },
    {
      id: 'occupancy-neha-green',
      societyId: greenSocietyId,
      unitId: findUnitId(greenSocietyId, 'A-202'),
      userId: 'user-neha',
      category: 'tenant',
      startDate: '2026-02-01',
    },
    {
      id: 'occupancy-rohan-green',
      societyId: greenSocietyId,
      unitId: findUnitId(greenSocietyId, 'B-101'),
      userId: 'user-rohan',
      category: 'owner',
      startDate: '2024-07-01',
    },
    {
      id: 'occupancy-kavya-palm',
      societyId: palmSocietyId,
      unitId: findUnitId(palmSocietyId, 'Plot 11'),
      userId: 'user-kavya',
      category: 'tenant',
      startDate: '2026-01-01',
    },
  ],
  vehicleRegistrations: [
    {
      id: 'vehicle-aarav-a101',
      societyId: greenSocietyId,
      userId: DEMO_USER_ID,
      unitId: findUnitId(greenSocietyId, 'A-101'),
      registrationNumber: 'GJ01AB1234',
      vehicleType: 'car',
      color: 'Pearl white',
      parkingSlot: 'Tower A P1-12',
    },
    {
      id: 'vehicle-neha-a202',
      societyId: greenSocietyId,
      userId: 'user-neha',
      unitId: findUnitId(greenSocietyId, 'A-202'),
      registrationNumber: 'GJ01CD7788',
      vehicleType: 'scooter',
      color: 'Midnight blue',
      parkingSlot: 'Tower A P1-21',
    },
    {
      id: 'vehicle-rohan-b101',
      societyId: greenSocietyId,
      userId: 'user-rohan',
      unitId: findUnitId(greenSocietyId, 'B-101'),
      registrationNumber: 'GJ01EF4567',
      vehicleType: 'car',
      color: 'Granite grey',
      parkingSlot: 'Tower B P2-04',
    },
    {
      id: 'vehicle-aarav-p07',
      societyId: palmSocietyId,
      userId: DEMO_USER_ID,
      unitId: findUnitId(palmSocietyId, 'Plot 07'),
      registrationNumber: 'GJ27LM9901',
      vehicleType: 'car',
      color: 'Forest green',
      parkingSlot: 'Driveway 07',
    },
    {
      id: 'vehicle-kavya-p11',
      societyId: palmSocietyId,
      userId: 'user-kavya',
      unitId: findUnitId(palmSocietyId, 'Plot 11'),
      registrationNumber: 'GJ27PQ9012',
      vehicleType: 'bike',
      color: 'Jet black',
      parkingSlot: 'Driveway 11',
    },
  ],
  importantContacts: [
    {
      id: 'contact-green-chairman',
      societyId: greenSocietyId,
      category: 'management',
      name: 'Aarav Mehta',
      roleLabel: 'Chairman desk',
      phone: '+91 98980 11111',
      availability: '9:00 AM - 7:00 PM',
      notes: 'Use for approvals, resident coordination, and urgent escalations.',
    },
    {
      id: 'contact-green-security',
      societyId: greenSocietyId,
      category: 'security',
      name: 'Main gate desk',
      roleLabel: 'Security control room',
      phone: '+91 98980 77777',
      availability: '24 x 7',
      notes: 'Visitor issues, parcel coordination, and gate access support.',
    },
    {
      id: 'contact-green-maintenance',
      societyId: greenSocietyId,
      category: 'maintenance',
      name: 'Service helpdesk',
      roleLabel: 'Maintenance support',
      phone: '+91 98980 12121',
      availability: '8:00 AM - 8:00 PM',
      notes: 'Water, lift, common-area repairs, and vendor follow-up.',
    },
    {
      id: 'contact-green-emergency',
      societyId: greenSocietyId,
      category: 'emergency',
      name: 'City emergency desk',
      roleLabel: 'Ambulance and fire support',
      phone: '112',
      availability: '24 x 7',
      notes: 'Call immediately for medical, fire, or safety emergencies.',
    },
    {
      id: 'contact-palm-manager',
      societyId: palmSocietyId,
      category: 'management',
      name: 'Estate office',
      roleLabel: 'Community manager',
      phone: '+91 98980 45454',
      availability: '9:30 AM - 6:30 PM',
      notes: 'General society coordination, event approvals, and owner queries.',
    },
    {
      id: 'contact-palm-security',
      societyId: palmSocietyId,
      category: 'security',
      name: 'Club gate security',
      roleLabel: 'Security desk',
      phone: '+91 98980 99999',
      availability: '24 x 7',
      notes: 'Entry approvals, parcel checks, and patrol support.',
    },
    {
      id: 'contact-palm-maintenance',
      societyId: palmSocietyId,
      category: 'maintenance',
      name: 'On-call electrician',
      roleLabel: 'Electrical maintenance',
      phone: '+91 98980 56565',
      availability: '8:00 AM - 10:00 PM',
      notes: 'Street light, clubhouse, and power backup issues.',
    },
    {
      id: 'contact-palm-amenity',
      societyId: palmSocietyId,
      category: 'amenity',
      name: 'Community hall desk',
      roleLabel: 'Amenity bookings',
      phone: '+91 98980 67676',
      availability: '10:00 AM - 8:00 PM',
      notes: 'Party lawn, hall, and guest parking support.',
    },
  ],
  announcements: [
    {
      id: 'announcement-green-water',
      societyId: greenSocietyId,
      title: 'Water tank cleaning on 21 Mar',
      body: 'Water supply will pause from 11:00 AM to 2:00 PM while both towers undergo cleaning.',
      audience: 'all',
      createdAt: '2026-03-18T06:00:00.000Z',
      priority: 'high',
      readByUserIds: ['user-neha'],
    },
    {
      id: 'announcement-green-agm',
      societyId: greenSocietyId,
      title: 'AGM scheduled for 24 Mar',
      body: 'Agenda includes FY26 maintenance revision, CCTV expansion, and clubhouse usage policy.',
      audience: 'owners',
      createdAt: '2026-03-15T11:30:00.000Z',
      priority: 'normal',
      readByUserIds: [DEMO_USER_ID, 'user-rohan'],
    },
    {
      id: 'announcement-palm-landscape',
      societyId: palmSocietyId,
      title: 'Landscape pruning this weekend',
      body: 'Party lawn and peripheral walking track will remain partially closed between 7:00 AM and 1:00 PM.',
      audience: 'all',
      createdAt: '2026-03-17T08:15:00.000Z',
      priority: 'normal',
      readByUserIds: [],
    },
  ],
  rules: [
    {
      id: 'rule-green-bylaws',
      societyId: greenSocietyId,
      title: 'Resident handbook',
      version: 'v1.3',
      summary: 'Waste segregation is mandatory. Amenity quiet hours start at 10 PM.',
      publishedAt: '2026-02-28T09:00:00.000Z',
      acknowledgementRequired: true,
      acknowledgedByUserIds: ['user-neha', 'user-rohan'],
    },
    {
      id: 'rule-palm-bylaws',
      societyId: palmSocietyId,
      title: 'Villa guidelines',
      version: 'v1.1',
      summary: 'Landscape access remains open except during event bookings and maintenance windows.',
      publishedAt: '2026-02-18T09:00:00.000Z',
      acknowledgementRequired: true,
      acknowledgedByUserIds: [DEMO_USER_ID],
    },
  ],
  amenities: [...greenAmenitySetup.amenities, ...palmAmenitySetup.amenities],
  amenityScheduleRules: [...greenAmenitySetup.rules, ...palmAmenitySetup.rules],
  bookings: [
    {
      id: 'booking-green-clubhouse',
      amenityId: `${greenSocietyId}-amenity-clubhouse-hall`,
      societyId: greenSocietyId,
      userId: DEMO_USER_ID,
      unitId: findUnitId(greenSocietyId, 'A-101'),
      date: '2026-03-23',
      startTime: '18:00',
      endTime: '21:00',
      status: 'pending',
      guests: 35,
    },
    {
      id: 'booking-palm-community',
      amenityId: `${palmSocietyId}-amenity-community-hall`,
      societyId: palmSocietyId,
      userId: 'user-kavya',
      unitId: findUnitId(palmSocietyId, 'Plot 11'),
      date: '2026-03-22',
      startTime: '10:00',
      endTime: '13:00',
      status: 'confirmed',
      guests: 18,
    },
  ],
  maintenancePlans: [
    {
      id: 'plan-green-monthly',
      societyId: greenSocietyId,
      frequency: 'monthly',
      dueDay: 10,
      amountInr: 6500,
      lateFeeInr: 250,
      calculationMethod: 'fixed',
      receiptPrefix: 'GVA',
      upiId: 'greenvalley@okicici',
      upiPayeeName: 'Green Valley Residency',
    },
    {
      id: 'plan-palm-monthly',
      societyId: palmSocietyId,
      frequency: 'monthly',
      dueDay: 8,
      amountInr: 5200,
      lateFeeInr: 200,
      calculationMethod: 'fixed',
      receiptPrefix: 'PMB',
      upiId: 'palmmeadows@okhdfcbank',
      upiPayeeName: 'Palm Meadows Business Park',
    },
  ],
  expenseRecords: [
    {
      id: 'expense-green-pump',
      societyId: greenSocietyId,
      expenseType: 'maintenance',
      title: 'Water pump servicing',
      amountInr: 12000,
      incurredOn: '2026-03-12',
      notes: 'Quarterly service and replacement of worn pressure valve.',
      createdByUserId: DEMO_USER_ID,
      createdAt: '2026-03-12T10:30:00.000Z',
    },
    {
      id: 'expense-palm-lighting',
      societyId: palmSocietyId,
      expenseType: 'adhoc',
      title: 'Gate light emergency repair',
      amountInr: 3800,
      incurredOn: '2026-03-10',
      notes: 'Temporary repair until the full lighting audit is completed.',
      createdByUserId: DEMO_USER_ID,
      createdAt: '2026-03-10T09:00:00.000Z',
    },
  ],
  invoices: [
    {
      id: 'invoice-green-aarav-mar',
      societyId: greenSocietyId,
      unitId: findUnitId(greenSocietyId, 'A-101'),
      planId: 'plan-green-monthly',
      periodLabel: 'Mar 2026',
      dueDate: '2026-03-10',
      amountInr: 6500,
      status: 'overdue',
    },
    {
      id: 'invoice-green-neha-mar',
      societyId: greenSocietyId,
      unitId: findUnitId(greenSocietyId, 'A-202'),
      planId: 'plan-green-monthly',
      periodLabel: 'Mar 2026',
      dueDate: '2026-03-10',
      amountInr: 6500,
      status: 'paid',
    },
    {
      id: 'invoice-green-rohan-mar',
      societyId: greenSocietyId,
      unitId: findUnitId(greenSocietyId, 'B-101'),
      planId: 'plan-green-monthly',
      periodLabel: 'Mar 2026',
      dueDate: '2026-03-10',
      amountInr: 6500,
      status: 'pending',
    },
    {
      id: 'invoice-palm-aarav-mar',
      societyId: palmSocietyId,
      unitId: findUnitId(palmSocietyId, 'Plot 07'),
      planId: 'plan-palm-monthly',
      periodLabel: 'Mar 2026',
      dueDate: '2026-03-08',
      amountInr: 5200,
      status: 'paid',
    },
  ],
  payments: [
    {
      id: 'payment-green-neha-mar',
      societyId: greenSocietyId,
      invoiceId: 'invoice-green-neha-mar',
      amountInr: 6500,
      method: 'upi',
      paidAt: '2026-03-06T13:20:00.000Z',
      status: 'captured',
      submittedByUserId: 'user-neha',
      reviewedByUserId: DEMO_USER_ID,
      reviewedAt: '2026-03-06T13:25:00.000Z',
      referenceNote: 'UPI ref 240156',
    },
    {
      id: 'payment-palm-aarav-mar',
      societyId: palmSocietyId,
      invoiceId: 'invoice-palm-aarav-mar',
      amountInr: 5200,
      method: 'netbanking',
      paidAt: '2026-03-04T09:15:00.000Z',
      status: 'captured',
      submittedByUserId: DEMO_USER_ID,
      reviewedByUserId: DEMO_USER_ID,
      reviewedAt: '2026-03-04T09:17:00.000Z',
      referenceNote: 'HDFC transfer confirmation',
    },
  ],
  paymentReminders: [
    {
      id: 'reminder-green-mar-overdue',
      societyId: greenSocietyId,
      invoiceIds: ['invoice-green-aarav-mar', 'invoice-green-rohan-mar'],
      unitIds: [findUnitId(greenSocietyId, 'A-101'), findUnitId(greenSocietyId, 'B-101')],
      message: 'March maintenance is still pending. Please flag the payment or contact the office desk if already transferred.',
      sentByUserId: DEMO_USER_ID,
      sentAt: '2026-03-18T08:30:00.000Z',
    },
  ],
  receipts: [
    {
      id: 'receipt-green-neha-mar',
      societyId: greenSocietyId,
      paymentId: 'payment-green-neha-mar',
      number: 'GVA-2401',
      issuedAt: '2026-03-06T13:25:00.000Z',
    },
    {
      id: 'receipt-palm-aarav-mar',
      societyId: palmSocietyId,
      paymentId: 'payment-palm-aarav-mar',
      number: 'PMB-1808',
      issuedAt: '2026-03-04T09:17:00.000Z',
    },
  ],
  complaints: [
    {
      id: 'complaint-green-lift',
      societyId: greenSocietyId,
      unitId: findUnitId(greenSocietyId, 'A-101'),
      createdByUserId: DEMO_USER_ID,
      category: 'general',
      title: 'Lift vibration near Tower A',
      status: 'open',
      createdAt: '2026-03-18T12:15:00.000Z',
      assignedTo: 'Lift contractor',
    },
    {
      id: 'complaint-green-basement',
      societyId: greenSocietyId,
      unitId: findUnitId(greenSocietyId, 'B-101'),
      createdByUserId: 'user-rohan',
      category: 'cleaning',
      title: 'Basement seepage near parking slot B17',
      status: 'inProgress',
      createdAt: '2026-03-16T10:05:00.000Z',
      assignedTo: 'Facility manager',
    },
    {
      id: 'complaint-palm-light',
      societyId: palmSocietyId,
      unitId: findUnitId(palmSocietyId, 'Plot 07'),
      createdByUserId: DEMO_USER_ID,
      category: 'security',
      title: 'Street light blinking near gate 2',
      status: 'resolved',
      createdAt: '2026-03-11T18:00:00.000Z',
      assignedTo: 'Electrical vendor',
    },
  ],
  complaintUpdates: [
    {
      id: 'complaint-update-green-lift-open',
      complaintId: 'complaint-green-lift',
      societyId: greenSocietyId,
      createdByUserId: DEMO_USER_ID,
      status: 'open',
      assignedTo: 'Lift contractor',
      message: 'Lift is vibrating during peak hours near Tower A. Please inspect the cabin alignment.',
      createdAt: '2026-03-18T12:15:00.000Z',
    },
    {
      id: 'complaint-update-green-basement-open',
      complaintId: 'complaint-green-basement',
      societyId: greenSocietyId,
      createdByUserId: 'user-rohan',
      status: 'open',
      assignedTo: null,
      message: 'Water seepage is spreading near parking slot B17 and the walkway edge.',
      createdAt: '2026-03-16T10:05:00.000Z',
    },
    {
      id: 'complaint-update-green-basement-progress',
      complaintId: 'complaint-green-basement',
      societyId: greenSocietyId,
      createdByUserId: SUPER_USER_ID,
      status: 'inProgress',
      assignedTo: 'Facility manager',
      message: 'Plumber visit scheduled for this afternoon. Temporary absorbent pads have been placed.',
      createdAt: '2026-03-16T13:30:00.000Z',
    },
    {
      id: 'complaint-update-palm-light-open',
      complaintId: 'complaint-palm-light',
      societyId: palmSocietyId,
      createdByUserId: DEMO_USER_ID,
      status: 'open',
      assignedTo: null,
      message: 'Street light near gate 2 keeps flickering after 7 PM.',
      createdAt: '2026-03-11T18:00:00.000Z',
    },
    {
      id: 'complaint-update-palm-light-resolved',
      complaintId: 'complaint-palm-light',
      societyId: palmSocietyId,
      createdByUserId: SUPER_USER_ID,
      status: 'resolved',
      assignedTo: 'Electrical vendor',
      message: 'Starter and wiring joint replaced. Light is stable now.',
      createdAt: '2026-03-12T09:20:00.000Z',
    },
  ],
  staffProfiles: [
    {
      id: 'staff-sunita',
      societyId: greenSocietyId,
      name: 'Sunita Ben',
      phone: '+91 98980 55555',
      category: 'cook',
      verificationState: 'verified',
      employerUnitIds: [findUnitId(greenSocietyId, 'A-101'), findUnitId(greenSocietyId, 'B-101')],
    },
    {
      id: 'staff-ravi',
      societyId: palmSocietyId,
      name: 'Ravi Driver',
      phone: '+91 98980 66666',
      category: 'driver',
      verificationState: 'pending',
      employerUnitIds: [findUnitId(palmSocietyId, 'Plot 07')],
    },
  ],
  staffAssignments: [
    {
      id: 'staff-assignment-sunita-a101',
      staffId: 'staff-sunita',
      societyId: greenSocietyId,
      unitId: findUnitId(greenSocietyId, 'A-101'),
      serviceLabel: 'Cooking and kitchen prep',
      visitsPerWeek: 6,
      active: true,
    },
    {
      id: 'staff-assignment-ravi-p07',
      staffId: 'staff-ravi',
      societyId: palmSocietyId,
      unitId: findUnitId(palmSocietyId, 'Plot 07'),
      serviceLabel: 'Driver and errands',
      visitsPerWeek: 6,
      active: true,
    },
  ],
  securityGuards: [
    {
      id: 'guard-mahesh',
      societyId: greenSocietyId,
      name: 'Mahesh Yadav',
      phone: '+91 98980 77777',
      shiftLabel: 'Day',
      vendorName: 'SecureNest Services',
    },
    {
      id: 'guard-jignesh',
      societyId: greenSocietyId,
      name: 'Jignesh Parmar',
      phone: '+91 98980 88888',
      shiftLabel: 'Night',
      vendorName: 'SecureNest Services',
    },
    {
      id: 'guard-kishore',
      societyId: palmSocietyId,
      name: 'Kishore Rana',
      phone: '+91 98980 99999',
      shiftLabel: 'Day',
      vendorName: 'GateCore Security',
    },
  ],
  securityShifts: [
    {
      id: 'shift-mahesh',
      guardId: 'guard-mahesh',
      societyId: greenSocietyId,
      start: '2026-03-19T06:00:00.000Z',
      end: '2026-03-19T14:00:00.000Z',
      gate: 'Main gate',
    },
    {
      id: 'shift-jignesh',
      guardId: 'guard-jignesh',
      societyId: greenSocietyId,
      start: '2026-03-19T22:00:00.000Z',
      end: '2026-03-20T06:00:00.000Z',
      gate: 'Service gate',
    },
    {
      id: 'shift-kishore',
      guardId: 'guard-kishore',
      societyId: palmSocietyId,
      start: '2026-03-19T07:00:00.000Z',
      end: '2026-03-19T19:00:00.000Z',
      gate: 'Club gate',
    },
  ],
  entryLogs: [
    {
      id: 'entry-sunita',
      societyId: greenSocietyId,
      subjectType: 'staff',
      subjectName: 'Sunita Ben',
      unitId: findUnitId(greenSocietyId, 'A-101'),
      enteredAt: '2026-03-19T07:10:00.000Z',
      status: 'inside',
    },
    {
      id: 'entry-amazon',
      societyId: palmSocietyId,
      subjectType: 'delivery',
      subjectName: 'Amazon parcel',
      unitId: findUnitId(palmSocietyId, 'Plot 07'),
      enteredAt: '2026-03-19T09:20:00.000Z',
      status: 'exited',
    },
  ],
};

module.exports = {
  DEMO_USER_ID,
  SUPER_USER_ID,
  amenityLibrary,
  defaultSetupDraft,
  seedData,
};
